name: CI - Build Lambda & Upload Artifacts

on:
  push:
    branches: ["feature/rag_pipeline"]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Config AWS CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: '0' 


    # 1. Build Lambda Ingest
    - name: Build ingest lambda
      run: |
        cd assets/ingest_lambda
        # pip install -r requirements.txt -t .
        zip -r ingest.zip .
        cd ../../
    - name: Upload ingest artifact
      run: |
        aws s3 cp assets/ingest_lambda/ingest.zip \
          s3://${{ secrets.ARTIFACT_BUCKET }}/ingest-${{ github.sha }}.zip
